// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ1vktswCIsyNJspdu4zDrLtiCJdTthLw',
    appId: '1:12929521913:web:8dc7bb065f615221f8aa28',
    messagingSenderId: '12929521913',
    projectId: 'catalog-app-4238f',
    authDomain: 'catalog-app-4238f.firebaseapp.com',
    storageBucket: 'catalog-app-4238f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo8ucHsEJgS_csbCLdtXMJo6K5UnC5lGg',
    appId: '1:12929521913:android:6516c97cb0de5eebf8aa28',
    messagingSenderId: '12929521913',
    projectId: 'catalog-app-4238f',
    storageBucket: 'catalog-app-4238f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2WYEoOqzR2I18acbAC9yWNlCpGFhmNBM',
    appId: '1:12929521913:ios:e9c29ad22f933be4f8aa28',
    messagingSenderId: '12929521913',
    projectId: 'catalog-app-4238f',
    storageBucket: 'catalog-app-4238f.appspot.com',
    iosClientId: '12929521913-uh00t3n4e3gstl555b9241ef7jlvfl7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterForTrial',
  );
}
